// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Index);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "สินค้าขายดี !");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Kanit26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Index);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_height(ui_Panel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Panel3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFF1800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label3, "ราคารวม VAT");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_product_price = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_product_price, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_product_price, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_product_price, -203);
    lv_obj_set_y(ui_product_price, 0);
    lv_obj_set_align(ui_product_price, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_product_price, "200.-");
    lv_obj_set_style_text_color(ui_product_price, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_product_price, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_product_price, &ui_font_Segment60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_product_image = lv_img_create(ui_Index);
    lv_img_set_src(ui_product_image, &ui_img_988204808);
    lv_obj_set_width(ui_product_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_product_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_product_image, -20);
    lv_obj_set_y(ui_product_image, 25);
    lv_obj_set_align(ui_product_image, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_product_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_product_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container3, 25);
    lv_obj_set_y(ui_Container3, 70);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_product_name = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_product_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_product_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_product_name, 24);
    lv_obj_set_y(ui_product_name, 74);
    lv_label_set_text(ui_product_name, "Raspberry Pi 5");
    lv_obj_set_style_text_font(ui_product_name, &ui_font_Kanit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_product_detail = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_product_detail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_product_detail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_product_detail, 24);
    lv_obj_set_y(ui_product_detail, 113);
    lv_label_set_text(ui_product_detail, "แรม 8GB");
    lv_obj_set_style_text_font(ui_product_detail, &ui_font_Kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_product_barcode_box = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_product_barcode_box);
    lv_obj_set_width(ui_product_barcode_box, 80);
    lv_obj_set_height(ui_product_barcode_box, 80);
    lv_obj_set_x(ui_product_barcode_box, 27);
    lv_obj_set_y(ui_product_barcode_box, 153);
    lv_obj_clear_flag(ui_product_barcode_box, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
