// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_product_price;
extern lv_obj_t * ui_product_image;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_product_name;
extern lv_obj_t * ui_product_detail;
extern lv_obj_t * ui_product_barcode_box;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_988204808);    // assets/ex-image.png



LV_FONT_DECLARE(ui_font_Kanit26);
LV_FONT_DECLARE(ui_font_Kanit20);
LV_FONT_DECLARE(ui_font_Segment60);
LV_FONT_DECLARE(ui_font_Kanit30);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
